### ISSUE TITLE
Support for visionOS

### ISSUE THREAD

**Issue by chhetri-rahul** [apple/swift-crypto#196]
When will the support for visionOS be provided, for both simulator and physical device?

We have a SDK which consumes swift-cryto as a package dependency (v 2.1.0). We are updating our codebase to support the new OS from Apple.

Right now when i build from cli with command:

xcodebuild -workspace MySDK.xcworkspace -configuration Debug -sdk xrsimulator build -derivedDataPath ./out -scheme MySDK -destination "generic/platform=visionOS Simulator,OS=latest,name=Apple Vision Pro" "ARCHS=\\x86_64 \\arm64

if fails with the error:

no such module 'CCryptoBoringSSL'
@_implementationOnly import CCryptoBoringSSL

**Comment by Lukasa** [comment]
v2.1.0 is very old, it was released in April 2022. Can you update to 2.6.0 and tell me if this reproduces?

**Comment by chhetri-rahul** [comment]
After updating to v2.6.0 we are getting the following compilation error

<img width="1409" alt="error-img" src="https://github.com/apple/swift-crypto/assets/18361235/d1289fde-afaa-424c-a31b-7191700a0da7">

[Here](https://github.com/grpc/grpc-swift/issues/1063) you suggested to change the build setting `BUILD_LIBRARY_FOR_DISTRIBUTION` as false which is not possible in our case.

And regarding the consumption of these APIs we are already importing using the `@_implementationOnly import` statement.


Can you please guide on how to fix this?

**Comment by Lukasa** [comment]
You must change the build setting _for swift-crypto_ to disable `BUILD_LIBRARY_FOR_DISTRIBUTION`: we do not have a stable ABI and we don't support this build mode.

You may subsequently link this library into a different library that you own which _does_ have a stable ABI, which is where `@_implementationOnly` will be helpful.

**Comment by Lukasa** [comment]
Additionally: are you actually using `_CryptoExtras`? If not, you could drop the dependency.

**Comment by chhetri-rahul** [comment]
Changing the build setting `BUILD_LIBRARY_FOR_DISTRIBUTION` also didn't help and it fails with the same error

I had updated this setting for both the targets (Crypto, _CryptoExtras) like below:

![Screenshot 2023-08-30 at 4 10 18 PM](https://github.com/apple/swift-crypto/assets/18361235/02cd7deb-376c-4901-a7f0-0f950cf67f19)


Also, `_CryptoExtras` is required by us and cannot be removed. We use `_RSA.Signing.Padding` from this module.

Btw this error can be seen in a standalone project as well when we try to archive it by running cli command.

Anything else that we can try?

**Comment by Lukasa** [comment]
Sorry, how do you reproduce this in a standalone project?

**Comment by chhetri-rahul** [comment]
Btw the failure is not related to visionOS, it fails for iphoneos as well (havent checked for other destinations) .

**Comment by Lukasa** [comment]
So I _believe_ that `BUILD_LIBRARY_FOR_DISTRIBUTION=YES` may be overriding the build setting in the package. Can you provide the build log?

**Comment by chhetri-rahul** [comment]
[archive-failed.txt](https://github.com/apple/swift-crypto/files/12485161/archive-failed.txt)

I noticed the archive commands succeeds when i remove `BUILD_LIBRARY_FOR_DISTRIBUTION=YES` from the command. But it is one thing we can't remove.

**Comment by Lukasa** [comment]
Yeah, that setting is overriding your change to the Package. Why can't you change the build setting for the package?

**Comment by FredericJacobs** [comment]
Renaming the issue to reflect the issue is not related to visionOS

**Comment by chhetri-rahul** [comment]
> Yeah, that setting is overriding your change to the Package. Why can't you change the build setting for the package?

I did change the build setting for the Crypto and _CryptoExtras in my fork and used it in my code but still got the same error.

**Comment by Lukasa** [comment]
Sorry, I meant to say: why does your project require setting `BUILD_LIBRARY_FOR_DISTRIBUTION=YES` on _all_ targets in your project?

**Comment by chhetri-rahul** [comment]
Not all the targets in the project require this setting, just two of them.

**Comment by Lukasa** [comment]
Is there any reason you cannot set this setting only for those two?

**Comment by chhetri-rahul** [comment]
@Lukasa can you help me tell how to set the build setting for individual targets?. Should i set this setting in xcode build settings ui and let terminal use the values from there or in command line i have to pass the setting to each target.

For the latter case how will the xcodebuild command look like.

**Comment by Lukasa** [comment]
You would set this in the Xcode build settings UI for the specific targets.

**Comment by chhetri-rahul** [comment]
Thanks @Lukasa i will try what you suggested. 

I also found [this](https://github.com/MarcoEidinger/swift-crypto/commit/5ff8bb3030d808570f1f2f04b4d3101ee3a860cc) when looking for a solution. The archive command succeeds with this change. 
[archive-success.txt](https://github.com/apple/swift-crypto/files/12594058/archive-success.txt)

Will removing @inlineable like in above cause any kind of problem in our code?

**Comment by Lukasa** [comment]
It may lead to worse performance, but that’s it

**Comment by chhetri-rahul** [comment]
Thanks @Lukasa for being patient in answering all the questions i have and for actively replying.

The performance degrade youre saying is only during build time or when the code gets used when app is running?

Also I tried what you suggested above and it fixes the archive failure problem, the only thing i want to know now is that we have 6 targets in our workspace (framework targets, unit tests, app targets) the setting BUILD_LIBRARY_FOR_DISTRIBUTION=YES is just to be passed to the framework target right?.

We distribute xcframework so i guess only having this setting in framework target is enough but want your opinion on it.

**Comment by Lukasa** [comment]
The performance degradation will be while the app is running.

And yes, you should only need to pass that value to the framework target.

**Comment by chhetri-rahul** [comment]
Okay Thank you very much @Lukasa 🤝🎉
