### PR TITLE
Add CMake build files

### PR DESCRIPTION
**Pull request by yim-lee**
Motivation:
This is to support https://github.com/apple/swift-package-manager/pull/3202, which adds swift-crypto as a dependency to SwiftPM.

Modifications:
Add CMake files.

Result:
Can build swift-crypto with cmake.

### CODE REVIEW

**Comment by yim-lee** [comment]
@compnerd @neonichu - please review

**Comment by neonichu** [comment]
Do we need to make sure we carry this define with us to keep Windows support? https://github.com/apple/swift-crypto/blob/main/Package.swift#L57 @compnerd

**Comment by Lukasa** [comment]
Do we have any plan to keep the CMakeLists.txt up-to-date?

**Comment by yim-lee** [comment]
Marking this a draft since there are build errors

```
[293/305] Building C object Sources/CCryptoBoringSSLShims/CMakeFiles/CCryptoBoringSSLShims.dir/shims.c.o
FAILED: Sources/CCryptoBoringSSLShims/CMakeFiles/CCryptoBoringSSLShims.dir/shims.c.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -ISources/CCryptoBoringSSLShims/include -Iswift -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -mmacosx-version-min=11.0 -MD -MT Sources/CCryptoBoringSSLShims/CMakeFiles/CCryptoBoringSSLShims.dir/shims.c.o -MF Sources/CCryptoBoringSSLShims/CMakeFiles/CCryptoBoringSSLShims.dir/shims.c.o.d -o Sources/CCryptoBoringSSLShims/CMakeFiles/CCryptoBoringSSLShims.dir/shims.c.o   -c Sources/CCryptoBoringSSLShims/shims.c
In file included from Sources/CCryptoBoringSSLShims/shims.c:14:
Sources/CCryptoBoringSSLShims/include/CCryptoBoringSSLShims.h:22:10: fatal error: 'CCryptoBoringSSL.h' file not found
#include <CCryptoBoringSSL.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
```

> Do we have any plan to keep the CMakeLists.txt up-to-date?

@Lukasa - we might be able to use env var instead of hardcoding the list of files but I could be wrong.

**Comment by neonichu** [comment]
> Do we have any plan to keep the CMakeLists.txt up-to-date?

Maybe we can add building with CMake as a step to CI so that there would at least be feedback if a PR breaks it?

**Comment by Lukasa** [comment]
I think we will absolutely have to do @neonichu's suggestion, irregardless of anything else. If we don't add that step I guarantee that we'll break you down the road because I'll 100% forget to make sure this still works.

However, the other problem we have is that you're currently explicitly naming every single file in the CBoringSSL target. This target's files are updated as a monolithic block with some regularity, and the exact files in there have high churn. Is there some way we can express the list of files by way of a glob? If not, I think I'd like us to invest in some scripting to automatically generate the file list for a given target. This should be fairly easy, as right now we're just following the rules that SwiftPM lays out. Essentially I want some way to say "look at this Package.swift and generate the appropriate CMakeLists.txt equivalent". I don't think this is particularly technically challenging, but would drastically reduce the maintenance burden of the CMake build system.

File: Sources/CCryptoBoringSSLShims/CMakeLists.txt [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+target_include_directories(CCryptoBoringSSLShims PUBLIC
+  include)
+
+target_link_libraries(CCryptoBoringSSLShims PUBLIC
+  CCryptoBoringSSL)
+  
+set_target_properties(CCryptoBoringSSLShims PROPERTIES
+  INTERFACE_INCLUDE_DIRECTORIES ${CMAKE_Swift_MODULE_DIRECTORY})
+  
+_install_target(CCryptoBoringSSLShims)
```
Comment (compnerd) [inline Sources/CCryptoBoringSSLShims/CMakeLists.txt:23]: Is there a reason to install the shims?  It is a static library, it does not need to be distributed correct?

File: Sources/CCryptoBoringSSL/CMakeLists.txt [hunk 2]
```diff
@@ -0,0 +1,322 @@
...
+  crypto/x509v3/v3_skey.c
+  crypto/x509v3/v3_utl.c)
+
+target_include_directories(CCryptoBoringSSL PUBLIC
+  include)
+  
+set_target_properties(CCryptoBoringSSL PROPERTIES
+  INTERFACE_INCLUDE_DIRECTORIES ${CMAKE_Swift_MODULE_DIRECTORY})
+  
+_install_target(CCryptoBoringSSL)
```
Comment (compnerd) [inline Sources/CCryptoBoringSSL/CMakeLists.txt:320]: Is there a reason to install the boring ssl target?  It is a static library and should not be used by consumers right?

File: Sources/Crypto/CMakeLists.txt [hunk 3]
```diff
@@ -0,0 +1,81 @@
...
+#
+# Copyright (c) 2021 Apple Inc. and the SwiftCrypto project authors
+# Licensed under Apache License v2.0
+#
+# See LICENSE.txt for license information
+# See CONTRIBUTORS.md for the list of SwiftCrypto project authors
+#
+# SPDX-License-Identifier: Apache-2.0
+
+add_library(Crypto
```
Comment (compnerd) [inline Sources/Crypto/CMakeLists.txt:11]: Should this be a static library or a shared library?  At least on Windows, static linking doesn't work yet, and needs to be shared.

File: CMakeLists.txt [hunk 4]
```diff
@@ -0,0 +1,31 @@
...
+if(CMAKE_VERSION VERSION_LESS 3.16 AND CMAKE_SYSTEM_NAME STREQUAL Windows)
+  set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
+  set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
+else()
+  set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
+  set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
+endif()
+set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
+set(CMAKE_Swift_MODULE_DIRECTORY ${CMAKE_BINARY_DIR}/swift)
+
```
Comment (compnerd) [inline CMakeLists.txt:29]: I think that for Windows at least (if not also Darwin) we should default to shared libraries:

```cmake
if(CMAKE_SYSTEM_NAME STREQUAL Windows OR CMAKE_SYSTEM_NAME STREQUAL Darwin)
  option(BUILD_SHARED_LIBS "Build shared libraries by default" YES)
endif()
```

File: Sources/CCryptoBoringSSL/CMakeLists.txt [hunk 5]
```diff
@@ -0,0 +1,322 @@
...
+  crypto/x509v3/v3_prn.c
+  crypto/x509v3/v3_purp.c
+  crypto/x509v3/v3_skey.c
+  crypto/x509v3/v3_utl.c)
+
+target_include_directories(CCryptoBoringSSL PUBLIC
+  include)
+  
+set_target_properties(CCryptoBoringSSL PROPERTIES
+  INTERFACE_INCLUDE_DIRECTORIES ${CMAKE_Swift_MODULE_DIRECTORY})
```
Comment (compnerd) [inline Sources/CCryptoBoringSSL/CMakeLists.txt:318]: I think that we need to set `WIN32_LEAN_AND_MEAN` as the generated files for boring ssl cause issues otherwise.  Something like this should do the trick:

```cmake
target_compile_definitions(CCryptoBoringSSL PRIVATE
  $<$<PLATFORM_ID:Windows>:WIN32_LEAN_AND_MEAN>)
```

**Comment by compnerd** [comment]
The problem with using a GLOB for the file list is that any changes will **not** be picked up.  You will need to remember that you changed things and do a _clean_ build.  I think that generating the file-list should be possible and would be a much nicer approach to just update the list as part of the generation script (as the updates are scripted).

File: Sources/CCryptoBoringSSL/CMakeLists.txt (hunk 2 above)
Comment (yim-lee) [reply Sources/CCryptoBoringSSL/CMakeLists.txt:320]: We have a use-case where `CCryptotBoringSSL` will be imported. Does this mean we need to make `CCryptotBoringSSL` shared?

Comment (compnerd) [reply Sources/CCryptoBoringSSL/CMakeLists.txt:320]: When you say imported, I assume you mean that another project will import it for use as a dependency from the Swift library correct?

In that case, I have to ask the follow up question of: is the import from a build tree or an install tree?

Use from the build tree is _extremely_ convenient as it allows for dependent projects to be built without installation - you simply pull content from the build output of a collection of projects and get the final installed set.  In this case, I think that we can get away without installing, just exporting the target for static linking.

If your usage is that you wish to build and install Crypto as a static library for use in a different project and then use the installed image for a dependency, then, yes you would need to install it.

Comment (yim-lee) [reply Sources/CCryptoBoringSSL/CMakeLists.txt:320]: > When you say imported, I assume you mean that another project will import it for use as a dependency from the Swift library correct?

The way we currently use it is that we depend on the "Crypto" module then do `import CCryptotBoringSSL` in source file. Can we achieve this without installing `CCryptotBoringSSL`?

Comment (compnerd) [reply Sources/CCryptoBoringSSL/CMakeLists.txt:320]: So, that depends on how the access to `Crypto` module is made (for build dependencies).  Does the consuming project simply do `find_package(SwiftCrypto)` and the expectation is that it is pointing to the build tree for SwiftCrypto?  If so, yes, I believe that we can get away without installing the module.

However, if the usage is not via CMake but rather because swift-crypto was installed into the system as a statically built library, then we would need to install the dependencies.  That is the reason that I was asking for more details about the desired usage.

I think that we _might_ be able to workaround the installation of the support libraries if absolutely required, but I think that once we know what the expected usage pattern is, we can make an appropriate choice.

**Comment by neonichu** [comment]
I think we should be able to script this using `swift package describe` which will tell us the list of source files according to SwiftPM rules.

File: Sources/CCryptoBoringSSL/CMakeLists.txt (hunk 2 above)
Comment (yim-lee) [reply Sources/CCryptoBoringSSL/CMakeLists.txt:320]: The consuming project is SwiftPM and I think we will do `find_package(SwiftCrypto)`, just like `TSC`, `ArgumentParser`, etc., so I will remove the `install_target` call.

File: Sources/Crypto/CMakeLists.txt (hunk 3 above)
Comment (yim-lee) [reply Sources/Crypto/CMakeLists.txt:11]: You mean this should say `add_library(Crypto SHARED`? The examples that I've looked at don't specify `SHARED` and only the C modules have `STATIC`.

File: Sources/CCryptoBoringSSLShims/CMakeLists.txt [hunk 6]
```diff
@@ -0,0 +1,25 @@
...
+# SPDX-License-Identifier: Apache-2.0
+
+add_library(CCryptoBoringSSLShims STATIC
+  shims.c)
+
+target_include_directories(CCryptoBoringSSLShims PUBLIC
+  include)
+
+target_link_libraries(CCryptoBoringSSLShims PUBLIC
+  CCryptoBoringSSL)
```
Comment (yim-lee) [inline Sources/CCryptoBoringSSLShims/CMakeLists.txt:18]: @compnerd `CCryptoBoringSSLShims` fails to build and I don't know how to fix it:

```
In file included from Sources/CCryptoBoringSSLShims/shims.c:14:
Sources/CCryptoBoringSSLShims/include/CCryptoBoringSSLShims.h:22:10: fatal error: 'CCryptoBoringSSL.h' file not found
#include <CCryptoBoringSSL.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.
```

`CCryptoBoringSSL.h` is in `CCryptoBoringSSL/include`, which we include:

```
target_include_directories(CCryptoBoringSSL PUBLIC
   include)
```

And we link `CCryptoBoringSSL` here.

Are we doing something wrong or something is missing?

Comment (compnerd) [reply Sources/CCryptoBoringSSLShims/CMakeLists.txt:18]: Hmm, because the include is marked as `PUBLIC` it should propagate to the user, and allow it to find it.

File: Sources/Crypto/CMakeLists.txt (hunk 3 above)
Comment (compnerd) [reply Sources/Crypto/CMakeLists.txt:11]: Well, the current signature leaves it in the control of the user.  If you specify `-D BUILD_SHARED_LIBS=YES` then this is implicitly a dynamic library and otherwise (or if you do `-D BUILD_SHARED_LIBS=NO`) it is implicitly a static library.  The reason for not specifying an explicit shared/static here is to allow the user to select the build type.  This is why setting the default value for `BUILD_SHARED_LIBS` to `YES` is what I suggested above.

File: Sources/CCryptoBoringSSLShims/CMakeLists.txt (hunk 6 above)
Comment (compnerd) [reply Sources/CCryptoBoringSSLShims/CMakeLists.txt:18]: #62 has the changes needed for this - feel free to pick up the changes and merge them here.

**Comment by tomerd** [comment]
> I think we will absolutely have to do @neonichu's suggestion, irregardless of anything else. If we don't add that step I guarantee that we'll break you down the road because I'll 100% forget to make sure this still works.

lmk if and when we need to set a CI job for this

**Comment by yim-lee** [comment]
@swift-server-bot test this please

**Comment by yim-lee** [comment]
Not sure how https://github.com/apple/swift-crypto/pull/60/commits/5f805719f61810b85370d57aefd42757db4aa725 causes these errors.

https://ci.swiftserver.group/job/swift-crypto-api-breakage-prb/68/console 

```
23:11:03 [337/384] Compiling Crypto EllipticCurvePoint_boring.swift
23:11:03 <unknown>:0: warning: missing submodule 'Dispatch'
23:11:03 <unknown>:0: error: cannot load underlying module for 'Dispatch'
23:11:04 [338/384] Compiling Crypto AES-GCM.swift
23:11:04 <unknown>:0: warning: missing submodule 'CCryptoBoringSSL'
23:11:04 /tmp/.check-api_Kwg0eL/repo/Sources/Crypto/AEADs/AES/GCM/BoringSSL/AES-GCM_boring.swift:17:29: error: no such module 'CCryptoBoringSSL'
23:11:04 @_implementationOnly import CCryptoBoringSSL
```

@swift-server-bot test this please

File: Sources/CCryptoBoringSSLShims/CMakeLists.txt (hunk 6 above)
Comment (yim-lee) [reply Sources/CCryptoBoringSSLShims/CMakeLists.txt:19]: Thanks @compnerd. I tested that it works on Ubuntu 20.04 (`swift:5.3-focal`) (needed https://github.com/apple/swift-crypto/pull/60/commits/5f805719f61810b85370d57aefd42757db4aa725 though):

```
apt-get update && apt-get install -y cmake ninja-build

cmake -G Ninja -D BUILD_SHARED_LIBS=YES -D CMAKE_BUILD_TYPE=Release -B out -S .
ninja
```

On macOS however, we'd need `CryptoKit`:

```
Sources/Crypto/Digests/HashFunctions.swift:18:24: error: cannot find type 'CoreCryptoDigestImpl' in scope
typealias DigestImpl = CoreCryptoDigestImpl
                       ^~~~~~~~~~~~~~~~~~~~
Sources/Crypto/Digests/HashFunctions.swift:30:28: error: cannot find type 'CryptoKit' in scope
    associatedtype Digest: CryptoKit.Digest
```

I tried https://github.com/apple/swift-crypto/pull/60/commits/b20d61504a50b74cd3f3a7df09d5d0203387dead but it's no good.

**Comment by yim-lee** [comment]
@swift-server-bot test this please

File: CMakeLists.txt [hunk 7]
```diff
@@ -0,0 +1,45 @@
...
+project(SwiftCrypto
+  LANGUAGES C Swift)
+
+list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/cmake/modules)
+
+include(SwiftSupport)
+
+# Fixes error: "requires dynamic R_X86_64_PC32 reloc against 'XXX' which may overflow at runtime"
+set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fPIC")
```
Comment (compnerd) [inline CMakeLists.txt:21]: Ah, yes, we should definitely be building in PIC mode, but this is the wrong way to accomplish that.  You should use the following:

```cmake
set(CMAKE_POSITION_INDEPENDENT_CODE YES)
```

However, that is not entirely for free either.  I think that for static builds, where SwiftCrypto is not being exported, it makes sense to be non-PIC (as it will be internal, the linker should be able to resolve everything relatively.  We could try something like this I suppose:

```cmake
if(BUILD_SHARED_LIBS)
  set(CMAKE_POSITION_INDEPENDENT_CODE YES)
endif()
```

File: Sources/CCryptoBoringSSLShims/CMakeLists.txt (hunk 6 above)
Comment (compnerd) [reply Sources/CCryptoBoringSSLShims/CMakeLists.txt:19]: The Darwin handling is supposed to be different because ... well, Apple.  Im not convinced that the CryptoKit variant is correct, but if you say it is, then it might be.  The thing is that `CryptoKit` is a framework, not a library so the linking is different.  However, I did update compnerd/swift-crypto (apple/swift-crypto#62) with the changes to link against CryptoKit).  It doesn't build locally for me due to missing typealiases (maybe I just have an older Xcode).

Comment (compnerd) [reply Sources/CCryptoBoringSSLShims/CMakeLists.txt:19]: Okay, compnerd/swift-crypto 9989bd67885d6685cebfb2741c19acdb9aba4357 has the changes to build SwiftCrypto on macOS with BoringSSL using the SwiftPM forced build approach.  I do not know what the correct thing is, so you will need to help guide the right solution here.

Comment (yim-lee) [reply Sources/CCryptoBoringSSLShims/CMakeLists.txt:19]: Thanks. I tried 

```
  target_link_options(Crypto PRIVATE
    "$<$<PLATFORM_ID:Darwin>:SHELL:-Xlinker -framework -Xlinker ${CRYPTO_KIT}>")
```

and it didn't work for me either. I got the same errors as [before](https://github.com/apple/swift-crypto/pull/60#discussion_r562444344).

Using `CRYPTO_IN_SWIFTPM_FORCE_BUILD_API` works. I assume this has to do with how `CryptoKit` is used specifically in this library. I tried importing another framework (`Security`) and actually didn't need to do anything extra (i.e., linking).

Comment (compnerd) [reply Sources/CCryptoBoringSSLShims/CMakeLists.txt:19]: Most of the frameworks on macOS work without the correct dependency tracking due to auto-linking which adds implicit dependencies that the build system doesn't know about.  It is always a good idea to be explicit about it.

**Comment by yim-lee** [comment]
"soundess" validation failure is expected until https://github.com/apple/swift-crypto/pull/63 gets merged

**Comment by yim-lee** [comment]
This is ready for review.

File: .gitignore [hunk 8]
```diff
@@ -13,3 +13,8 @@ DerivedData
 **/gyb.pyc
 
 .*.sw[nop]
+
+CMakeFiles
+CMakeCache.txt
+cmake_*.cmake
```
Comment (compnerd) [inline .gitignore:19]: I'm not sure that there should be added.  We really should be discouraging in-tree builds, requiring out of tree builds.  I'd be okay with ignoring common output directories:

/out/
/.build/
/build/

But the listed files shouldn't be created.

If we are okay with using undocumented features, there is a way to prevent the in-tree builds IIRC.

File: Sources/CCryptoBoringSSL/CMakeLists.txt [hunk 9]
```diff
@@ -0,0 +1,345 @@
...
+      crypto/fipsmodule/rdrand-x86_64.mac.x86_64.S
+      crypto/fipsmodule/rsaz-avx2.mac.x86_64.S
+      crypto/fipsmodule/sha1-x86_64.mac.x86_64.S
+      crypto/fipsmodule/sha256-x86_64.mac.x86_64.S
+      crypto/fipsmodule/sha512-x86_64.mac.x86_64.S
+      crypto/fipsmodule/vpaes-x86_64.mac.x86_64.S
+      crypto/fipsmodule/x86_64-mont.mac.x86_64.S
+      crypto/fipsmodule/x86_64-mont5.mac.x86_64.S)
+  endif()
+endif()
```
Comment (compnerd) [inline Sources/CCryptoBoringSSL/CMakeLists.txt:335]: We should cover windows and Linux as well, but that is okay to have as a follow up.

File: scripts/check_no_api_breakages.sh [hunk 10]
```diff
@@ -36,6 +36,7 @@ function build_and_do() {
     (
     cd "$repodir"
     git checkout -q "$tag"
+    rm -rf .build
```
Comment (compnerd) [inline scripts/check_no_api_breakages.sh:39]: Might deserve a comment - it's unclear to me why this change is needed.

**Comment by yim-lee** [comment]
I added `scripts/update_cmakelists.txt` (https://github.com/apple/swift-crypto/pull/60/commits/beac548802375f981fed850bbd20933bece59e72) that finds source files under a directory then updates that specific part of the corresponding `CMakeLists.txt`. Hopefully that makes things easier?

File: Sources/CCryptoBoringSSL/CMakeLists.txt (hunk 9 above)
Comment (yim-lee) [reply Sources/CCryptoBoringSSL/CMakeLists.txt:335]: Which ones are for Windows? I don't see any `*x86_64*` for it.

Comment (compnerd) [reply Sources/CCryptoBoringSSL/CMakeLists.txt:335]: Windows has some assembly routines for x86, not for x64.  I don't think that it matters too much if we don't get that variant correct.  I don't currently intend to ship a 32-bit toolchain.  For Windows x86, use of swift-crypto as a client should go through SPM, which will handle it properly.  If someone intends to ship a non-x64 variant of the toolchain, we should handle it at that time.

**Comment by yim-lee** [comment]
Build error unrelated. Looks like build agent 1 is busted.

@swift-server-bot test this please

File: Sources/CCryptoBoringSSL/CMakeLists.txt (hunk 9 above)
Comment (yim-lee) [reply Sources/CCryptoBoringSSL/CMakeLists.txt]: OK. Added Linux https://github.com/apple/swift-crypto/pull/60/commits/6d2e5c1567a3bad8560c0478e370f35475d998da

**Comment by yim-lee** [comment]
Updated `soundness.sh` to check for source file changes that would require updating `CMakeLists.txt`, in which case CI would fail and prevent merge (for non-admin at least).

**Comment by yim-lee** [comment]
@tomerd build agent for 5.3 is still no good: https://ci.swiftserver.group/job/swift-crypto-swift53-prb/59/console

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by compnerd** [comment]
LGTM FWIW

File: scripts/update_cmakelists.sh [hunk 11]
```diff
@@ -0,0 +1,60 @@
...
+    # Update list of source files in CMakeLists.txt
+    # The first part in `BEGIN` (i.e., `undef $/;`) is for working with multi-line;
+    # the second is so that we can pass in a variable to replace with.
+    perl -pi -e 'BEGIN { undef $/; $replace = shift } s/add_library\(([^\n]+)\n([^\)]+)/add_library\($1\n$replace/' "$srcs" "$src_root/CMakeLists.txt"
+    echo "Updated $src_root/CMakeLists.txt"
+}
+
+update_cmakelists "CCryptoBoringSSL" "*.c"
+update_cmakelists "CCryptoBoringSSLShims" "*.c"
+update_cmakelists "Crypto" "*.swift"
```
Comment (Lukasa) [inline scripts/update_cmakelists.sh:60]: Are we not generating the `.S` list on purpose?

Comment (yim-lee) [reply scripts/update_cmakelists.sh:60]: Just wasn't sure if they change often. Sounds like we should generate?

Comment (Lukasa) [reply scripts/update_cmakelists.sh:60]: If we can, yeah. They do change with some frequency.

Comment (yim-lee) [reply scripts/update_cmakelists.sh]: Amended https://github.com/apple/swift-crypto/pull/60/commits/937bdd36a14c5e45da4cb2f1917bc8d17850515c

**Review by Lukasa — APPROVED** [review]
Ok, I think this will work. Thanks for making it something we can maintain going forward @yim-lee, and thanks for your help along the way @compnerd and @neonichu.
